language: node_js
node_js:
  - 10
after_success:
  - npm run cover
before_deploy:
  - npm install
  - npm run ci:build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: example/build
  on:
    branch: master